
 /*

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 find the sum of the even-valued terms.
*/
#include <stdio.h>

#define CEILING 4000000
int main() 
{
        int term1 = 0, term2 = 1, next, result = 0;
        while(next < CEILING) {
                if( next % 2 == 0) result+=next;
                next = term1 + term2;
                term1 = term2;
                term2 = next;

        }
        printf("%d\n", result);

}